/**
 *
 * $Id$
 */
package tictactoe.validation;

import org.eclipse.emf.common.util.EList;

import tictactoe.Mark;
import tictactoe.Player;
import tictactoe.Square;

/**
 * A sample validator interface for {@link tictactoe.Engine}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EngineValidator {
	boolean validate();

	boolean validateIsOTurn(Boolean value);
	boolean validatePlayer(EList<Player> value);
	boolean validateSquare(EList<Square> value);

	boolean validateBlackPlayer(Player value);

	boolean validateWhitePlayer(Player value);

	boolean validateMark(EList<Mark> value);

	boolean validateWhiteWlayer(Player value);

	boolean validateBlackPlayer(EList<Player> value);

	boolean validateWhiteWlayer(EList<Player> value);
}
