/**
 *
 * $Id$
 */
package tictactoe.validation;

import tictactoe.Color;
import tictactoe.Square;

/**
 * A sample validator interface for {@link tictactoe.Mark}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarkValidator {
	boolean validate();

	boolean validateColor(Color value);
	boolean validatePos_x(int value);
	boolean validatePos_y(int value);
	boolean validateSquare(Square value);
}
